name: Build and Upload to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Focando no Ubuntu para garantir estabilidade e evitar erros de rede do macOS
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          # FILTRO:
          # 1. cp36-cp38: Versões obsoletas
          # 2. pp*: Pula PyPy (evita erros de C++)
          # 3. *-manylinux_i686: Pula Linux 32-bit
          # 4. *-musllinux_i686: Pula Alpine 32-bit
          CIBW_SKIP: cp36-* cp37-* cp38-* pp* *-manylinux_i686 *-musllinux_i686
          
          # ESTRATÉGIA ANTI-COMPILAÇÃO:
          # Fixamos o numpy e proibimos o pip de compilar do código-fonte (só aceita binários)
          CIBW_TEST_REQUIRES: numpy==1.26.4
          CIBW_ENVIRONMENT: PIP_ONLY_BINARY=:all:
          
          CIBW_TEST_COMMAND: python -c "import strkernels; print('Sucesso:', strkernels.__all__)"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  publish:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-wheels-*
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}